package dev.fede.module;

/**
 * Inventory of every module registered in feClient.
 *
 * SOURCE KEY:
 *   [NAT]   — from the native base client (dev.sixseven → dev.fede)
 *   [NYX]  — from CodeEngine (dev.nyx → dev.fede.nyx)
 *   [H2O]  — from WaterSRC   (com.water → dev.fede.water)
 *
 * Modules that appear in multiple clients are registered ONCE using
 * the best implementation (generally the native base client's for shared ones).
 * Unique modules from each client all appear.
 *
 * ─── COMBAT ───────────────────────────────────────────────────────
 *  AutoCrystal          [NAT+NYX+H2O]   — native-base impl (most advanced)
 *  AutoTotem            [NAT+NYX+H2O]
 *  AutoInventoryTotem   [NAT+H2O]
 *  AnchorMacro          [NAT+H2O]
 *  DoubleAnchor         [NAT+H2O]
 *  AimAssist            [NAT]
 *  MaceSwap             [NAT]
 *  MaceBomber           [NAT]
 *  ElytraSwap           [NAT]
 *  HoverTotem           [NAT+H2O]
 *  ShieldBreaker        [NAT+H2O]
 *  Triggerbot           [NAT+NYX+H2O]
 *  HitBox               [NAT+NYX+H2O]
 *  KillAura             [NYX]
 *  Reach                [NYX]
 *  Velocity             [NYX]
 *  AntiKnockback        [NYX]
 *  Backtrack            [NYX]
 *  Criticals            [NYX]
 *  AutoArmor            [NYX]
 *  ChestStealer         [NYX]
 *  MaceAura             [NYX]
 *  AutoLog              [NYX+H2O]
 *  SingleAnchor         [H2O]
 *  SpearSwap            [H2O]
 *  AutoDoubleHand       [H2O]
 *
 * ─── MOVEMENT ─────────────────────────────────────────────────────
 *  AutoWalk             [NAT+NYX+H2O]
 *  FreeLook             [NAT+NYX+H2O]
 *  Freecam              [NAT+NYX+H2O]
 *  Sprint               [NYX+H2O]
 *  Speed                [NYX]
 *  Fly                  [NYX]
 *  ChunkSpoof           [NYX]
 *  AirJump              [NYX]
 *  AntiVoid             [NYX]
 *  EagleAura            [NYX]
 *  ElytraFly            [NYX]
 *  HighJump             [NYX]
 *  IceSpeed             [NYX]
 *  InventoryMove        [NYX]
 *  Jesus                [NYX]
 *  LongJump             [NYX]
 *  NoFall               [NYX]
 *  NoSlow               [NYX]
 *  Spider               [NYX]
 *  Step                 [NYX]
 *  Strafe               [NYX]
 *
 * ─── PLAYER ───────────────────────────────────────────────────────
 *  FastUse              [NAT+NYX]
 *  AutoTpa              [NAT+H2O]
 *  SwingSpeed           [NAT+H2O]
 *  CoordSnapper         [NAT+H2O]
 *  ChatMacro            [NAT+H2O]
 *  AutoClicker          [NAT+NYX]
 *  AntiAFK              [NYX]
 *  AutoEat              [NYX]
 *  AutoFish             [NYX]
 *  AutoTool             [NYX+H2O]
 *  AutoDrop             [NYX]
 *  AutoRespawn          [NYX]
 *  FastPlace            [NYX+H2O]
 *  MiddleClick          [NYX]
 *  NoJumpDelay          [NYX]
 *  PortalGodMode        [NYX]
 *  SwingAnimation       [NYX]
 *  AutoMine             [H2O]
 *  HomeSetter           [H2O]
 *  TabDetector          [H2O]
 *  TunnelBaseFinder     [H2O]
 *
 * ─── RENDER ───────────────────────────────────────────────────────
 *  PlayerEsp            [NAT+NYX+H2O]
 *  StorageEsp           [NAT+NYX+H2O]
 *  BlockEsp             [NAT+H2O]
 *  BlockEntityEsp       [NAT]
 *  DebugHoleEsp         [NAT+H2O]
 *  MobEsp               [NAT]
 *  FullBright           [NAT+NYX+H2O]
 *  Zoom                 [NAT+NYX]
 *  CustomFov            [NAT]
 *  CustomCrosshair      [NAT]
 *  CustomGlint          [NAT+NYX]
 *  JumpCircles          [NAT+H2O]
 *  NameTags             [NAT+NYX+H2O]
 *  MotionBlur           [NAT]
 *  HitParticles         [NAT+NYX]
 *  RegionMap            [NAT+NYX+H2O]
 *  SpawnerNametags      [NAT]
 *  ESP                  [NYX]
 *  NoHurtCam            [NYX]
 *  StashFinder          [NYX+H2O]
 *  MovementTrails       [NYX]
 *  ProjectileArc        [NYX]
 *  VoidEsp              [NYX]
 *  ItemEsp              [NYX]
 *  Chams                [NYX]
 *  CornerBoxEsp         [NYX]
 *  Outlines             [NYX]
 *  OutlineEsp           [NYX]
 *  Tracers              [NYX]
 *  Radar                [NYX]
 *  HealthTags           [NYX]
 *  ArrowEsp             [NYX]
 *  XRay                 [NYX]
 *  ClearWorld           [NYX]
 *  ItemPhysics          [NYX]
 *  ViewModel            [NYX]
 *  CauldronEsp          [NYX]
 *  BedEsp               [NYX]
 *  PortalEsp            [NYX]
 *  HeatMapChunkRadar    [NYX]
 *  RaidPlanner          [NYX]
 *  HoveredContainerPreview [NYX]
 *  SpectatorDetector    [NYX]
 *  PearlEsp             [H2O]
 *  ExtraEsp             [H2O]
 *  NoRender             [H2O]
 *  SpawnerNotifier      [H2O]
 *  SkinChanger          [H2O]
 *
 * ─── WORLD ────────────────────────────────────────────────────────
 *  Nuker                [NYX]
 *  Scaffold             [NYX]
 *  AutoBridge           [NYX]
 *  AutoTunnel           [NYX]
 *  AutoMLG              [NYX]
 *  AutoSmelt            [NYX]
 *  AutoStore            [NYX]
 *  AutoTree             [NYX]
 *  TimerSpeed           [NYX]
 *  InfoOrb              [NYX]
 *  RtpBaseFinder        [NYX]
 *  ChunkKeeper          [NYX]
 *  AutoRender           [H2O]
 *
 * ─── DONUT ────────────────────────────────────────────────────────
 *  ChunkFinder          [NAT+NYX]
 *  RegionMap            [NAT+NYX+H2O]   (registered once)
 *  SpawnerProtect       [NAT+NYX+H2O]
 *  FakeRoles            [NAT+H2O]
 *  FakeStats            [NAT+H2O]
 *  FakePay              [NAT]
 *  StaffList            [NAT+H2O]
 *  GambleRigger         [NAT]
 *  ArmorTrimHider       [NAT]
 *  AntiTrap             [NYX+H2O]
 *  AutoSell             [NYX]
 *  AutoSpawnerSell      [NYX]
 *  ItemDropper          [NYX]
 *  PrimeChunkFinder     [NYX]
 *  SeedChunkFinder      [NYX]
 *  BlockEntityDebug     [NYX]
 *  LightFinder          [NYX]
 *  PlayerChunks         [NYX]
 *  HoleEsp              [NYX+H2O]
 *  NetheriteFinder      [NYX]
 *  StaffDetector        [H2O]
 *  BoneDropper          [H2O]
 *  TuffChunkV2          [H2O]
 *  ActivityDebug        [H2O]
 *  SuspiciousChunkFinder [H2O]
 *
 * ─── ADDONS ───────────────────────────────────────────────────────
 *  CustomAccessories    [NAT]
 *  SkinProtect          [NAT]
 *  NameProtect          [NAT+H2O]
 *  WeatherNotifier      [NAT+H2O]
 *  BlockGlow            [NYX]
 *  BlockOutline         [NYX]
 *  GlintCustomiser      [NYX]
 *  BreakParticles       [NYX]
 *  DragonWings          [NYX]
 *  KillEffects          [NYX]
 *  PlayerParticles      [NYX]
 *
 * ─── CLIENT ───────────────────────────────────────────────────────
 *  HUD                  [NAT]
 *  ClickGUI             [NAT — NanoVG]
 *  Spotify              [NAT+NYX+H2O]
 *  ConfigShare          [NAT]
 *  Friends              [H2O]
 *  DiscordRPC           [NYX+H2O]
 *  CustomTitle          [NYX]
 *  KeystrokeHUD         [NYX]
 *  TargetHUD            [NYX]
 *  TabGUI               [NYX]
 *  ChatFilter           [NYX]
 *  ThemeSelector        [NYX]
 *  ChromaXP             [NYX]
 *  ClickSounds          [NYX]
 *  Nickname             [NYX]
 *  WaterPlus            [H2O]
 */
public final class MergedModuleManager {
    private MergedModuleManager() {}
}
